/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GlobalRouteImport } from './routes/global'
import { Route as DzRouteImport } from './routes/dz'
import { Route as IndexRouteImport } from './routes/index'

const GlobalRoute = GlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => rootRouteImport,
} as any)
const DzRoute = DzRouteImport.update({
  id: '/dz',
  path: '/dz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dz': typeof DzRoute
  '/global': typeof GlobalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dz': typeof DzRoute
  '/global': typeof GlobalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dz': typeof DzRoute
  '/global': typeof GlobalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dz' | '/global'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dz' | '/global'
  id: '__root__' | '/' | '/dz' | '/global'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DzRoute: typeof DzRoute
  GlobalRoute: typeof GlobalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/global': {
      id: '/global'
      path: '/global'
      fullPath: '/global'
      preLoaderRoute: typeof GlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dz': {
      id: '/dz'
      path: '/dz'
      fullPath: '/dz'
      preLoaderRoute: typeof DzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DzRoute: DzRoute,
  GlobalRoute: GlobalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
